alias ls='ls --color=auto'
alias gitd='git diff -b'
alias gitds='git diff --staged'
alias gitl='git log --oneline --graph --decorate --all'
alias gits='git status'
alias gitc='git restore . ; git clean -f'
alias gita='git add'
alias t='tmux new -A -s robone'
